language: node_js
node_js:
  - "11"
jobs:
  include:
    - stage: Build & Deploy
      if: branch = master
      cache: npm
      script:
        - npm i
        - npm run firebase:build
      deploy:
        provider: firebase
        skip_cleanup: true
        token:
          secure: e92Q/bToAvH4e0INfINjKoIi2VRDYT5R0eF9GalH3ANcCzkB4Zgqk46GVBHwA1TBByJo7Yxkn5uy2B6RWCJfPLIoFbGc6vi6aEYuCtvgZbFsZoE53DM3o84joFOFqkL1lx0mVd+x8nmhPs1T+Eqq7IJ39Sws+9lV8igQ/TrOCj4iK828QtPzm2mPUHkzth11Vp5m+DaUNb7lJZ7PLZ3clDwtk2KonGrt04HdBUkghIrXHa0jufVZ+KARwL85BMNNqehXTmp6MV5uPqxFG7RUU5StHC67j3fp86DX0cLFaHijjyYgqQwQaETou9uwi9cnJc/HDOobRO7gtRfDFLtFmTUioeRX7sjaOmw+dOF39sqccDHsUUgsXZ5P+CbocDirLFjwm8MTokI0e1xKx0sl5AZzaur8jM7RFTVWZWkqyyyFvnPuBkuwa+X16OLSdiF/cZjFNvHtXqfEIL7l/FBvhybSC4dZF1PFiYfxcEo9Xjt98hESXEWHLCMOFGYmG/dYNcoCmB8/Rw7MfLnvQHawk+dH4/yiXmNJAzzI8sAtjX0yVOcOppPFtT9KJ4NakCe5JuCnwDrxjPLGYCc6Xm890LWgBjkqJcSz9tuD/Zz82utD4zETb2bice0qzrdefzz1uYQI6nrOCm4w5NYh5eO5tBNyPERM7PEQLJWtV0goz2Q=
notifications:
  email: false
