language: node_js
node_js:
  - "11"
jobs:
  include:
    - stage: Deploy
      if: branch = master
      cache: npm
      script:
        - npm i
        - npm run build
      deploy:
        provider: pages
        local_dir: dist
        target-branch: gh-pages
        name: Travis Deployment Bot
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        fqdn: dev.buffalo311.org
        on:
          branch: master
  notifications:
    email: false
env:
  global:
    - secure: G5sBsY/HLb3+441Hr24FbxddUrPk14y3iEso3QwiOSxYasm+ZoAu8JPLPKC3tre0ujwhME3E0lSdE++UVNy8ktksASk/fxGSVzHZje/sFo5z6TU5+xPHrkUb0IoJs30FwKY26qKsf1zas/xGwdZG+r03J/uzKbQtUEXBL91NxiacnBxOe0nVb3dMMuqF3FdGKn0RvZ177yIEncxs0Ucpikk/2+s3Ra/1PBd3hHrePzCZ6EHj8eLtarnNuXQ4BZT5AGJjBlY/bFd0UxXhbJc28KiZGvIr+ThWeuj57xgmsOrK9m5jnJMhk6BEb7+KTh02/5lvFX9/WKTv0TFLm7JhgLxbPokMG5e4C8HKBEs/Z51q3ZIZ948Co6XENVwIbfhSVX7JZ6PLX/BE51WXYEr10HqIiXdyo7cDu0Og4Vo5+H6ey17YpvyMXGp7jQzFYOP2Y3htRt4PyUzWIgZZiE7uBjpnazCxccQAyDtF7Ad1btk+2/exgLfKTlcE8ady7YYJwL+M9q2xtjVtjiQthtsDs+N+sdsRwjwMdiMHeqQ5ehskohPJeNnKO4K5QMmO9rm19M0J/S4Qt/trApkj4TZMqvIiJD/wTTep2KmL3ngPQS1yoy0Z77ewl58ZHQ4y5tNTPZi+lrZhln+gFICwMQspW5+W7oaxZ3QkTbckcMccGRc=
